### ISSUE TITLE
Will the Netatmo security improvements break this Node?

### ISSUE THREAD

**Issue by Dunnenj** [tvecera/node-red-contrib-netatmo-energy#11]
Have you see the announcement from Netatmo for the API use? Is this node already use this method?

Dear Netatmo developer,
To improve the security of our products, we inform you that the Client Credentials grant type method will be completely removed. It will no longer be possible to authenticate with the username and password of the user. The effective date of this update is October 2022.

From this date, the OAuth2 authorization code flow must be followed for authentication.

You can find details on this method on our website:
https://dev.netatmo.com/apidocumentation/oauth#authorization-code

**Comment by tvecera** [comment]
Hi Dunnenj, yes after Netatmo removes the "Client Credentials" scope from its API, this custom node will stop working as well. I am working on a solution, hopefully I can find a way before Netatmo removes this authorization method.

**Comment by tvecera** [comment]
I just published a new version, [0.9.1](https://www.npmjs.com/package/node-red-contrib-netatmo-energy), introducing OAUTH authorization for the Netatmo API. You must obtain a Netatmo API refresh token to make this node work. You can get it manually or use my simple command line program [Netatmo Auth CLI](https://github.com/tvecera/netatmo-auth-cli).
