### ISSUE TITLE
support for switchschedule

### ISSUE THREAD

**Issue by bdormael** [tvecera/node-red-contrib-netatmo-energy#2]
Is there a possibility when using SETTHERMMODE and choose Schedule that we can also choose which schedule ?

According to the API this should be possible by adding a SCHEDULE_ID parameter.

Or adding support for the SWITCHHOMESCHEDULE API would suit the same purpose.

**Comment by tvecera** [comment]
SWITCHHOMESCHEDULE API  has been added in the latest version, v0.9.0.
