### ISSUE TITLE
Add node SwitchHomeSchedule

### ISSUE THREAD

**Issue by albertomitrani** [tvecera/node-red-contrib-netatmo-energy#4]
It should be very useful to have a node as per title with only two parameters:
1. home id
2 schedule id

here is the page of Netatmo API
Thank You very much for your support.

<img width="1409" alt="Schermata 2020-11-30 alle 12 12 39" src="https://user-images.githubusercontent.com/55845466/100603456-6eb2d980-3305-11eb-97db-d3c3f7386c1e.png">
API doc

**Comment by tvecera** [comment]
Added in new version 0.9.0
