### ISSUE TITLE
Home & Room id

### ISSUE THREAD

**Issue by BouldBadger** [tvecera/node-red-contrib-netatmo-energy#6]
I'm really sorry for putting this here but I wasn't sure how to get help with this..and have searched everywhere.
Where can I find the Home and Room id's - I just can't seem to locate them!

Thanks so much for the work you've put into this and any help would be great!!

**Comment by sadmin91** [comment]
Hello,
You can use homesdata node to give theses informations.
Regards

**Comment by BouldBadger** [comment]
Thank you!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
