### ISSUE TITLE
payload

### ISSUE THREAD

**Issue by matteos1** [tvecera/node-red-contrib-netatmo-energy#7]
how is it possible to insert a payload to change the temperature at Node SETTHERMMODE?

**Comment by tvecera** [comment]
Unfortunately, this is not possible. As you can see in the API definition from Netatmo, you cannot specify the temperature when setting the mode. 

https://dev.netatmo.com/apidocumentation/energy#setthermmode

The temperature for each mode must be set directly in the Netatmo app.
